# -*- coding: utf-8 -*-
"""Magnetic_ერთიანი.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lkeJsVJB2gsnnUMxJFiSG6fvdLgEJLdb

- 4x4
"""

import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt
import time

# Choose what to plot.  Set either option to False if you want only one type.
plot_raw_probabilities = True
plot_running_averages = True
plot_raw_loglog = True

# ============================================================
# INPUT PARAMETERS
# ============================================================

# General ordinary vector:
# omega = (omega_1, omega_2, omega_3)
omega_1 = float(input("Enter omega_1 [s^-1]: "))
omega_2 = float(input("Enter omega_2 [s^-1]: "))
omega_3 = float(input("Enter omega_3 [s^-1]: "))

# Choose whether |omega'| is fixed, changes linearly with time,
# or is scanned over several separate plots.
omega_prime_mode = input(
    "omega_prime mode: enter 'const', 'time', or 'val': "
).strip().lower()

if omega_prime_mode not in ("const", "time", "val"):
    raise ValueError("Enter exactly 'const', 'time', or 'val'.")

if omega_prime_mode == "const":
    omega_prime_const = float(
        input("Enter constant omega_prime [s^-1]: ")
    )
elif omega_prime_mode == "time":
    omega_prime_initial = float(
        input("Enter initial omega_prime [s^-1]: ")
    )
    omega_prime_final = float(
        input("Enter final omega_prime [s^-1]: ")
    )
else:  # 'val'
    omega_prime_start = float(
        input("Enter first omega_prime value [s^-1]: ")
    )
    omega_prime_step = float(
        input("Enter omega_prime step between plots [s^-1]: ")
    )
    number_of_plots = int(
        input("How many omega_prime values/plots do you want? ")
    )
    if number_of_plots < 1:
        raise ValueError("The number of plots must be at least 1.")

    omega_prime_values = (
        omega_prime_start + omega_prime_step * np.arange(number_of_plots)
    )
    if np.any(omega_prime_values < 0.0):
        raise ValueError("All omega_prime magnitudes must be non-negative.")

tau = float(input("Enter tau [s]: "))

# beta(t) is the angle between omega and omega'(t)
beta_mean_deg = float(input("Enter mean beta_0 [degrees]: "))
beta_amp_deg = float(input("Enter beta amplitude b [degrees]: "))
Limit_factor = float(input("Enter Limit_factor: "))

# Initial neutron spin angle relative to omega
alpha_deg = float(input("Enter initial alpha [degrees]: "))

T = float(input("Enter final time T [s]: "))

# ============================================================
# DERIVED QUANTITIES
# ============================================================

omega_vec = np.array([omega_1, omega_2, omega_3], dtype=float)
omega_mag = np.linalg.norm(omega_vec)

if omega_mag == 0.0:
    raise ValueError("The vector omega cannot be zero.")

if tau <= 0.0:
    raise ValueError("tau must be positive.")

if T <= 0.0:
    raise ValueError("T must be positive.")

beta_mean = np.deg2rad(beta_mean_deg)
beta_amp = np.deg2rad(beta_amp_deg)
alpha = np.deg2rad(alpha_deg)

epsilon = 1.0 / tau
Omega_beta = Limit_factor / tau

T_values = [T / 2.0, T]

num_time_points = 2000
rtol_value = 1e-9
atol_value = 1e-11

# ============================================================
# PAULI MATRICES
# ============================================================

sigma_x = np.array([
    [0, 1],
    [1, 0]
], dtype=complex)

sigma_y = np.array([
    [0, -1j],
    [1j, 0]
], dtype=complex)

sigma_z = np.array([
    [1, 0],
    [0, -1]
], dtype=complex)

I2 = np.eye(2, dtype=complex)

# ============================================================
# VECTOR HELPERS
# ============================================================

def omega_dot_sigma(vec):
    """
    vec . sigma = vec_x sigma_x + vec_y sigma_y + vec_z sigma_z
    """
    return (
        vec[0] * sigma_x
        + vec[1] * sigma_y
        + vec[2] * sigma_z
    )

# Unit vector along ordinary omega
e_omega = omega_vec / omega_mag

# This selects one fixed perpendicular direction and hence
# fixes the plane in which omega'(t) rotates.
reference = np.array([0.0, 0.0, 1.0])

if abs(np.dot(reference, e_omega)) > 0.99:
    reference = np.array([1.0, 0.0, 0.0])

e_perp = reference - np.dot(reference, e_omega) * e_omega
e_perp = e_perp / np.linalg.norm(e_perp)

# ============================================================
# TIME-DEPENDENT omega' MAGNITUDE AND DIRECTION
# ============================================================

def omega_prime_magnitude(t):
    """
    Magnitude |omega'(t)|.
    """

    if omega_prime_mode == "const":
        return omega_prime_const

    # Linear ramp: omega'_initial -> omega'_final in time T
    return (
        omega_prime_initial
        + (omega_prime_final - omega_prime_initial) * t / T
    )

def beta_of_time(t):
    """
    beta(t) = beta_mean + beta_amp sin(Omega_beta t)

    This is the angle between omega and omega'(t).
    """
    return beta_mean + beta_amp * np.sin(Omega_beta * t)

def omega_prime_vector_time(t, magnitude_override=None):
    """
    omega'(t) = |omega'(t)| [
        cos(beta(t)) e_omega + sin(beta(t)) e_perp
    ]
    """

    beta_t = beta_of_time(t)
    if magnitude_override is None:
        omega_prime_mag_t = omega_prime_magnitude(t)
    else:
        # Used in 'val' mode: fixed magnitude for one complete simulation.
        omega_prime_mag_t = magnitude_override

    direction = (
        np.cos(beta_t) * e_omega
        + np.sin(beta_t) * e_perp
    )

    return omega_prime_mag_t * direction

# ============================================================
# INITIAL SPIN STATE
# ============================================================

def spinor_from_direction(direction):
    """
    Returns a spin-1/2 state whose expectation value points
    along the supplied three-dimensional direction.
    """

    direction = direction / np.linalg.norm(direction)

    theta = np.arccos(np.clip(direction[2], -1.0, 1.0))
    phi = np.arctan2(direction[1], direction[0])

    return np.array([
        np.cos(theta / 2.0),
        np.exp(1j * phi) * np.sin(theta / 2.0)
    ], dtype=complex)

# The initial spin makes alpha with omega.
spin_direction_0 = (
    np.cos(alpha) * e_omega
    + np.sin(alpha) * e_perp
)

chi_n = spinor_from_direction(spin_direction_0)

# Basis: [n_up, n_down, nprime_up, nprime_down]
psi0 = np.array([
    chi_n[0],
    chi_n[1],
    0.0 + 0.0j,
    0.0 + 0.0j
], dtype=complex)

# ============================================================
# HAMILTONIAN
# ============================================================

def H_of_time(t, magnitude_override=None):
    """
    H(t) = [2 omega.sigma,           epsilon I]
           [epsilon I, 2 omega'(t).sigma]
    """

    omega_prime_vec = omega_prime_vector_time(t, magnitude_override)

    H_nn = 2.0 * omega_dot_sigma(omega_vec)
    H_nprime_nprime = 2.0 * omega_dot_sigma(omega_prime_vec)
    H_mix = epsilon * I2

    return np.block([
        [H_nn, H_mix],
        [H_mix, H_nprime_nprime]
    ])

def rhs(t, psi, magnitude_override=None):
    return -1j * H_of_time(t, magnitude_override) @ psi

# ============================================================
# PRINT PARAMETERS
# ============================================================

print("\nCalculated quantities:")
print(f"omega             = {omega_vec} s^-1")
print(f"|omega|           = {omega_mag:g} s^-1")
print(f"epsilon           = {epsilon:g} s^-1")
print(f"Omega_beta        = {Omega_beta:g} s^-1")
print(f"e_omega           = {e_omega}")
print(f"e_perp            = {e_perp}")

if omega_prime_mode == "const":
    print(f"omega'(t)         = {omega_prime_const:g} s^-1 (constant)")
elif omega_prime_mode == "time":
    omega_prime_slope = (
        omega_prime_final - omega_prime_initial
    ) / T
    print(
        f"|omega'(t)|       = {omega_prime_initial:g} s^-1"
        f" {omega_prime_slope:+g} t s^-2"
    )
else:
    print("omega' scan        = separate simulations with fixed magnitudes")
    print(f"omega'_start       = {omega_prime_start:g} s^-1")
    print(f"omega'_step        = {omega_prime_step:g} s^-1 per plot")
    print(f"number of plots    = {number_of_plots}")
    print(f"omega' values      = {omega_prime_values} s^-1")

print(
    f"beta(t)           = {beta_mean_deg:g} deg"
    f" + {beta_amp_deg:g} deg cos({Omega_beta:g} t)"
)

print("\nInitial spin direction:")
print(spin_direction_0)

print("\nInitial state psi(0):")
print(psi0)

print("\nVectors at selected times:")
for t_print in [0.0, T / 2.0, T]:
    print(f"\nt = {t_print:g} s")
    if omega_prime_mode == "val":
        displayed_omega_prime = omega_prime_values[0]
    else:
        displayed_omega_prime = omega_prime_magnitude(t_print)
    print(f"|omega'(t)| = {displayed_omega_prime:g} s^-1")
    print(f"beta(t) = {np.rad2deg(beta_of_time(t_print)):.4f} degrees")
    print(
        f"omega'(t) = "
        f"{omega_prime_vector_time(t_print, displayed_omega_prime)}"
    )

print("\nH(t=0):")
if omega_prime_mode == "val":
    print(H_of_time(0.0, omega_prime_values[0]))
else:
    print(H_of_time(0.0))

# ============================================================
# PROBABILITIES
# ============================================================

def probabilities(solution):

    P_n_up = np.abs(solution.y[0])**2
    P_n_down = np.abs(solution.y[1])**2

    P_nprime_up = np.abs(solution.y[2])**2
    P_nprime_down = np.abs(solution.y[3])**2

    P_n = P_n_up + P_n_down
    P_nprime = P_nprime_up + P_nprime_down
    P_total = P_n + P_nprime

    return (
        P_n_up,
        P_n_down,
        P_nprime_up,
        P_nprime_down,
        P_n,
        P_nprime,
        P_total
    )

# ============================================================
# RUNNING TIME AVERAGE
# ============================================================

def running_time_average(t_vals, P_vals):
    """
    Return the running average

        P_bar(t) = 1 / (t - t0) integral from t0 to t of P(t') dt'

    evaluated by cumulative trapezoidal integration.  The first point is
    omitted because the average is undefined at t = t0.
    """

    t_vals = np.asarray(t_vals)
    P_vals = np.asarray(P_vals)

    dt = np.diff(t_vals)
    trapezoid_areas = 0.5 * (P_vals[:-1] + P_vals[1:]) * dt
    cumulative_area = np.cumsum(trapezoid_areas)
    elapsed_time = t_vals[1:] - t_vals[0]

    return t_vals[1:], cumulative_area / elapsed_time

# ============================================================
# PLOT SETUP: RAW PROBABILITIES AND RUNNING AVERAGES IN FIGURES
# ============================================================

if omega_prime_mode == "val":
    # Each panel uses one fixed |omega'|, for the full interval 0 <= t <= T.
    ncols = min(3, number_of_plots)
    nrows = int(np.ceil(number_of_plots / ncols))
    panel_end_times = [T] * number_of_plots
    panel_omega_prime_values = omega_prime_values
elif omega_prime_mode == "time":
    # One plot: omega'(t) evolves continuously from t = 0 to t = T.
    ncols = 1
    nrows = 1
    panel_end_times = [T]
    panel_omega_prime_values = [None]
else:
    ncols = 2
    nrows = 1
    panel_end_times = [T / 2.0, T]
    panel_omega_prime_values = [None, None]

def make_figure():
    """Create figures with a consistent overall size."""

    if omega_prime_mode == "val":
        fig, axes = plt.subplots(
            nrows, ncols,
            figsize=(16, 8),
            sharey=True,
            squeeze=False
        )
    elif omega_prime_mode == "time":
        fig, axes = plt.subplots(
            1, 1,
            figsize=(16, 8)
        )
    else:
        fig, axes = plt.subplots(
            1, 2,
            figsize=(16, 8),
            sharey=True
        )

    return fig, np.atleast_1d(axes).ravel()

def plot_raw_curves(ax, t_vals, P_n, P_nprime, P_n_up, P_n_down,
                    P_nprime_up, P_nprime_down, P_total, loglog=False):
    """Plot all raw probabilities on linear axes or log-log axes."""

    def draw(values, **style):
        if loglog:
            # Logarithmic axes cannot display t = 0 or an exactly zero value.
            positive = (t_vals > 0.0) & (values > 0.0)
            ax.loglog(t_vals[positive], values[positive], **style)
        else:
            ax.plot(t_vals, values, **style)

    draw(P_n, color="black", linewidth=1.8, label=r"$P_n$")
    draw(P_nprime, color="green", linewidth=1.8, label=r"$P_{n'}$")
    draw(P_n_up, color="red", linewidth=0.9, label=r"$P_{n,\uparrow}$")
    draw(P_n_down, color="red", linestyle="--", linewidth=0.9,
         label=r"$P_{n,\downarrow}$")
    draw(P_nprime_up, color="orange", linewidth=0.9,
         label=r"$P_{n',\uparrow}$")
    draw(P_nprime_down, color="orange", linestyle="--", linewidth=0.9,
         label=r"$P_{n',\downarrow}$")
    draw(P_total, color="blue", linestyle=":", linewidth=1.0,
         label=r"$P_{\rm total}$")

fig_raw = axes_raw = None
fig_avg = axes_avg = None
fig_raw_loglog = axes_raw_loglog = None

if plot_raw_probabilities:
    fig_raw, axes_raw = make_figure()

if plot_running_averages:
    fig_avg, axes_avg = make_figure()

if plot_raw_loglog:
    fig_raw_loglog, axes_raw_loglog = make_figure()

start_time = time.perf_counter()

for i, (T_panel, omega_prime_panel) in enumerate(
    zip(panel_end_times, panel_omega_prime_values)
):

    t_values = np.linspace(0.0, T_panel, num_time_points)

    solution = solve_ivp(
        rhs,
        (0.0, T_panel),
        psi0,
        args=(omega_prime_panel,),
        t_eval=t_values,
        method="RK45",
        rtol=rtol_value,
        atol=atol_value
    )

    if not solution.success:
        raise RuntimeError(solution.message)

    (
        P_n_up,
        P_n_down,
        P_nprime_up,
        P_nprime_down,
        P_n,
        P_nprime,
        P_total
    ) = probabilities(solution)

    # Running averages of the total ordinary, mirror, and total populations.
    t_avg, P_n_avg = running_time_average(solution.t, P_n)
    _, P_nprime_avg = running_time_average(solution.t, P_nprime)
    _, P_total_avg = running_time_average(solution.t, P_total)

    if plot_raw_probabilities:
        ax_raw = axes_raw[i]
        plot_raw_curves(
            ax_raw, solution.t, P_n, P_nprime, P_n_up, P_n_down,
            P_nprime_up, P_nprime_down, P_total
        )

    if plot_raw_loglog:
        ax_raw_loglog = axes_raw_loglog[i]
        plot_raw_curves(
            ax_raw_loglog, solution.t, P_n, P_nprime, P_n_up, P_n_down,
            P_nprime_up, P_nprime_down, P_total, loglog=True
        )

    if plot_running_averages:
        ax_avg = axes_avg[i]
        ax_avg.plot(t_avg, P_n_avg, color="black",
                    linewidth=2.2, label=r"$\overline{P}_n$")
        ax_avg.plot(t_avg, P_nprime_avg, color="green",
                    linewidth=2.2, label=r"$\overline{P}_{n'}$")
        ax_avg.plot(t_avg, P_total_avg, color="blue",
                    linestyle=":", linewidth=1.8,
                    label=r"$\overline{P}_{\rm total}$")

    # Apply identical panel labels and axes formatting to both figures.
    for axes_set in (axes_raw, axes_avg, axes_raw_loglog):
        if axes_set is None:
            continue

        ax = axes_set[i]
        if omega_prime_mode == "val":
            ax.set_title(
                rf"$|\omega'|={omega_prime_panel:g}\,\mathrm{{s}}^{{-1}}$",
                fontsize=16
            )
        else:
            ax.set_title(rf"$T = {T_panel:g}\,\mathrm{{s}}$", fontsize=18)

        ax.set_xlabel(r"$t\,[\mathrm{s}]$", fontsize=18)
        ax.tick_params(axis="both", labelsize=15)
        ax.grid(True)

        if i % ncols == 0:
            ax.set_ylabel("Probability", fontsize=18)

end_time = time.perf_counter()
print(f"\nSimulation time: {end_time - start_time:.3f} seconds")

if omega_prime_mode == "const":
    omega_prime_title = rf"$\omega'={omega_prime_const:g}\,\mathrm{{s}}^{{-1}}$"
elif omega_prime_mode == "time":
    omega_prime_title = (
        rf"$\omega'(t)={omega_prime_initial:g}\,\mathrm{{s}}^{{-1}}"
        rf"{omega_prime_slope:+g}t\,\mathrm{{s}}^{{-2}}$"
    )
else:
    omega_prime_title = (
        rf"$|\omega'_k|={omega_prime_start:g}"
        rf"+k({omega_prime_step:g}),\quad k=0,\ldots,{number_of_plots - 1}$"
    )

if omega_prime_mode == "const":
    filename_stem = "four_state_constant_omega_prime"
elif omega_prime_mode == "time":
    filename_stem = "four_state_linear_time_dependent_omega_prime"
else:
    filename_stem = "four_state_omega_prime_value_scan"

def finish_figure(fig, axes, figure_name, filename, legend_columns):
    """Add common labels, hide unused scan cells, and save one figure."""

    if omega_prime_mode == "val":
        for ax in axes[number_of_plots:]:
            ax.set_visible(False)

    handles, labels = axes[0].get_legend_handles_labels()
    fig.suptitle(
        figure_name + ": "
        + rf"$\boldsymbol{{\omega}}=({omega_1:g}, {omega_2:g}, {omega_3:g})$, "
        + omega_prime_title + ", "
        + rf"$\alpha={alpha_deg:g}^\circ$, "
        + rf"$\beta(t)={beta_mean_deg:g}+{beta_amp_deg:g}^\circ\sin(\Omega_\beta t)$",
        fontsize=20,
        y=0.96
    )
    fig.legend(
        handles, labels,
        loc="upper center",
        ncol=7,
        fontsize=20,
        bbox_to_anchor=(0.5, 0.88)
    )
    fig.tight_layout(rect=[0, 0, 1, 0.80])


if plot_raw_probabilities:
    finish_figure(
        fig_raw, axes_raw, "4-state raw probabilities",
        filename_stem + "_raw_probabilities.png", 4
    )

if plot_running_averages:
    finish_figure(
        fig_avg, axes_avg, "4-state running time averages",
        filename_stem + "_running_time_averages.png", 3
    )

if plot_raw_loglog:
    finish_figure(
        fig_raw_loglog, axes_raw_loglog, "4-state raw probabilities (log-log)",
        filename_stem + "_rhaw_probabilities_loglog.png", 4
    )

plt.show()

"""- 8x8"""

import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt
import time

try:
    from IPython.display import display, Math
    in_notebook = True
except ImportError:
    in_notebook = False

# ============================================================
# PLOT OPTIONS
# ============================================================
plot_raw_probabilities = True
plot_running_averages = True
plot_raw_loglog = True

# ============================================================
# INPUT PARAMETERS
# ============================================================
omega_1 = float(input("Enter omega_1 [s^-1]: "))
omega_2 = float(input("Enter omega_2 [s^-1]: "))
omega_3 = float(input("Enter omega_3 [s^-1]: "))

omega_prime_mode = input(
    "omega_prime mode: enter 'const', 'time', or 'val': "
).strip().lower()
if omega_prime_mode not in ("const", "time", "val"):
    raise ValueError("Enter exactly 'const', 'time', or 'val'.")

if omega_prime_mode == "const":
    omega_prime_const = float(input("Enter constant omega_prime [s^-1]: "))
elif omega_prime_mode == "time":
    omega_prime_initial = float(input("Enter initial omega_prime [s^-1]: "))
    omega_prime_final = float(input("Enter final omega_prime [s^-1]: "))
else:
    omega_prime_start = float(input("Enter first omega_prime value [s^-1]: "))
    omega_prime_step = float(input("Enter omega_prime step between plots [s^-1]: "))
    number_of_plots = int(input("How many omega_prime values/plots do you want? "))
    if number_of_plots < 1:
        raise ValueError("The number of plots must be at least 1.")
    omega_prime_values = omega_prime_start + omega_prime_step * np.arange(number_of_plots)
    if np.any(omega_prime_values < 0.0):
        raise ValueError("All omega_prime magnitudes must be non-negative.")

tau = float(input("Enter tau [s]: "))
alpha_over_epsilon = float(input("Enter alpha / epsilon (dimensionless): "))

beta_mean_deg = float(input("Enter mean beta_0 [degrees]: "))
beta_amp_deg = float(input("Enter beta amplitude b [degrees]: "))
limit_factor = float(input("Enter Limit_factor: "))
spin_alpha_deg = float(input("Enter initial-spin angle [degrees]: "))
T = float(input("Enter final time T [s]: "))

omega_vec = np.array([omega_1, omega_2, omega_3], dtype=float)
omega_mag = np.linalg.norm(omega_vec)
if omega_mag == 0.0:
    raise ValueError("The vector omega cannot be zero.")
if tau <= 0.0:
    raise ValueError("tau must be positive.")
if T <= 0.0:
    raise ValueError("T must be positive.")

beta_mean = np.deg2rad(beta_mean_deg)
beta_amp = np.deg2rad(beta_amp_deg)
spin_alpha = np.deg2rad(spin_alpha_deg)
epsilon = 1.0 / tau
alpha_mix = alpha_over_epsilon * epsilon
Omega_beta = limit_factor / tau

print("\nCalculated mixing parameters:")
print(f"epsilon           = {epsilon:g} s^-1")
print(f"alpha / epsilon   = {alpha_over_epsilon:g}")
print(f"alpha             = {alpha_mix:g} s^-1")

num_time_points = 2000
rtol_value = 1e-9
atol_value = 1e-11

# ============================================================
# PAULI MATRICES AND DIRECTIONS
# ============================================================
sigma_x = np.array([[0, 1], [1, 0]], dtype=complex)
sigma_y = np.array([[0, -1j], [1j, 0]], dtype=complex)
sigma_z = np.array([[1, 0], [0, -1]], dtype=complex)
I2 = np.eye(2, dtype=complex)
zero2 = np.zeros((2, 2), dtype=complex)

def omega_dot_sigma(vec):
    return vec[0] * sigma_x + vec[1] * sigma_y + vec[2] * sigma_z

e_omega = omega_vec / omega_mag
reference = np.array([0.0, 0.0, 1.0])
if abs(np.dot(reference, e_omega)) > 0.99:
    reference = np.array([1.0, 0.0, 0.0])
e_perp = reference - np.dot(reference, e_omega) * e_omega
e_perp /= np.linalg.norm(e_perp)

def omega_prime_magnitude(t):
    if omega_prime_mode == "const":
        return omega_prime_const
    return omega_prime_initial + (omega_prime_final - omega_prime_initial) * t / T

def beta_of_time(t):
    return beta_mean + beta_amp * np.cos(Omega_beta * t)

def omega_prime_vector_time(t, magnitude_override=None):
    magnitude = omega_prime_magnitude(t) if magnitude_override is None else magnitude_override
    beta_t = beta_of_time(t)
    direction = np.cos(beta_t) * e_omega + np.sin(beta_t) * e_perp
    return magnitude * direction

# ============================================================
# INITIAL STATE
# Basis: [n_up, n_down, nbar_up, nbar_down,
#         nprime_up, nprime_down, nprimebar_up, nprimebar_down]
# ============================================================
def spinor_from_direction(direction):
    direction = direction / np.linalg.norm(direction)
    theta = np.arccos(np.clip(direction[2], -1.0, 1.0))
    phi = np.arctan2(direction[1], direction[0])
    return np.array([
        np.cos(theta / 2.0),
        np.exp(1j * phi) * np.sin(theta / 2.0)
    ], dtype=complex)

spin_direction_0 = np.cos(spin_alpha) * e_omega + np.sin(spin_alpha) * e_perp
chi_n = spinor_from_direction(spin_direction_0)
psi0 = np.array([chi_n[0], chi_n[1], 0j, 0j, 0j, 0j, 0j, 0j], dtype=complex)

# ============================================================
# 8-STATE HAMILTONIAN
# ============================================================
if in_notebook:
    display(Math(
        r"H_8="
        r"\begin{pmatrix}"
        r"\boldsymbol{2\omega}\cdot\boldsymbol{\sigma}&0&\varepsilon I_2&\alpha I_2\\"
        r"0&-\boldsymbol{2\omega}\cdot\boldsymbol{\sigma}&\alpha I_2&\varepsilon I_2\\"
        r"\varepsilon I_2&\alpha I_2&\boldsymbol{2\omega}'\cdot\boldsymbol{\sigma}&0\\"
        r"\alpha I_2&\varepsilon I_2&0&-\boldsymbol{2\omega}'\cdot\boldsymbol{\sigma}"
        r"\end{pmatrix}"
    ))

def H_of_time(t, magnitude_override=None):
    """8 x 8 Hamiltonian, written as four 2 x 2 spin blocks."""
    omega_sigma = omega_dot_sigma(omega_vec)
    omega_prime_sigma = omega_dot_sigma(
        omega_prime_vector_time(t, magnitude_override)
    )
    eps_block = epsilon * I2
    alpha_block = alpha_mix * I2
    return np.block([
        [2*omega_sigma,  zero2,         eps_block,         alpha_block],
        [zero2,        -2*omega_sigma,  alpha_block,       eps_block],
        [eps_block,    alpha_block,   2*omega_prime_sigma, zero2],
        [alpha_block,  eps_block,     zero2,             -2*omega_prime_sigma],
    ])

def rhs(t, psi, magnitude_override=None):
    return -1j * H_of_time(t, magnitude_override) @ psi

def probabilities(solution):
    P_n = np.abs(solution.y[0])**2 + np.abs(solution.y[1])**2
    P_nbar = np.abs(solution.y[2])**2 + np.abs(solution.y[3])**2
    P_nprime = np.abs(solution.y[4])**2 + np.abs(solution.y[5])**2
    P_nprimebar = np.abs(solution.y[6])**2 + np.abs(solution.y[7])**2
    return P_n, P_nbar, P_nprime, P_nprimebar, P_n + P_nbar + P_nprime + P_nprimebar

def running_time_average(t_vals, P_vals):
    dt = np.diff(t_vals)
    areas = 0.5 * (P_vals[:-1] + P_vals[1:]) * dt
    return t_vals[1:], np.cumsum(areas) / (t_vals[1:] - t_vals[0])

# ============================================================
# FIGURE LAYOUT
# ============================================================
if omega_prime_mode == "val":
    ncols = min(3, number_of_plots)
    nrows = int(np.ceil(number_of_plots / ncols))
    panel_end_times = [T] * number_of_plots
    panel_omega_prime_values = omega_prime_values
elif omega_prime_mode == "time":
    nrows, ncols = 1, 1
    panel_end_times = [T]
    panel_omega_prime_values = [None]
else:
    nrows, ncols = 1, 2
    panel_end_times = [T / 2.0, T]
    panel_omega_prime_values = [None, None]

def make_figure():
    if omega_prime_mode == "val":
        fig, axes = plt.subplots(nrows, ncols, figsize=(6*ncols, 4.8*nrows),
                                 sharey=True, squeeze=False)
    elif omega_prime_mode == "time":
        fig, axes = plt.subplots(1, 1, figsize=(10, 6))
    else:
        fig, axes = plt.subplots(1, 2, figsize=(16, 8), sharey=True)
    return fig, np.atleast_1d(axes).ravel()

def plot_curves(ax, t, probabilities_to_plot, labels, loglog=False, linewidth=1.8):
    colors = ["black", "red", "orange", "green", "blue"]
    styles = ["-", "-", "-", "-", ":"]
    for values, label, color, style in zip(probabilities_to_plot, labels, colors, styles):
        if loglog:
            mask = (t > 0.0) & (values > 0.0)
            ax.loglog(t[mask], values[mask], color=color, linestyle=style,
                      linewidth=linewidth, label=label)
        else:
            ax.plot(t, values, color=color, linestyle=style,
                    linewidth=linewidth, label=label)

fig_raw = axes_raw = None
fig_avg = axes_avg = None
fig_loglog = axes_loglog = None
if plot_raw_probabilities:
    fig_raw, axes_raw = make_figure()
if plot_running_averages:
    fig_avg, axes_avg = make_figure()
if plot_raw_loglog:
    fig_loglog, axes_loglog = make_figure()

start_time = time.perf_counter()
for i, (T_panel, omega_prime_panel) in enumerate(zip(panel_end_times, panel_omega_prime_values)):
    t_values = np.linspace(0.0, T_panel, num_time_points)
    solution = solve_ivp(rhs, (0.0, T_panel), psi0, args=(omega_prime_panel,),
                         t_eval=t_values, method="RK45", rtol=rtol_value, atol=atol_value)
    if not solution.success:
        raise RuntimeError(solution.message)

    P_n, P_nbar, P_nprime, P_nprimebar, P_total = probabilities(solution)
    probabilities_raw = [P_n, P_nbar, P_nprime, P_nprimebar, P_total]
    labels_raw = [r"$P_n$", r"$P_{\bar n}$", r"$P_{n'}$",
                  r"$P_{\bar n'}$", r"$P_{\rm total}$"]

    t_avg, P_n_avg = running_time_average(solution.t, P_n)
    _, P_nbar_avg = running_time_average(solution.t, P_nbar)
    _, P_nprime_avg = running_time_average(solution.t, P_nprime)
    _, P_nprimebar_avg = running_time_average(solution.t, P_nprimebar)
    _, P_total_avg = running_time_average(solution.t, P_total)
    probabilities_avg = [P_n_avg, P_nbar_avg, P_nprime_avg, P_nprimebar_avg, P_total_avg]
    labels_avg = [r"$\overline{P}_n$", r"$\overline{P}_{\bar n}$",
                  r"$\overline{P}_{n'}$", r"$\overline{P}_{\bar n'}$",
                  r"$\overline{P}_{\rm total}$"]

    if axes_raw is not None:
      plot_curves(axes_raw[i], solution.t, probabilities_raw, labels_raw)

    if axes_avg is not None:
      plot_curves(
      axes_avg[i], t_avg, probabilities_avg, labels_avg,
      linewidth=2.2
    )

    if axes_loglog is not None:
      plot_curves(
      axes_loglog[i], solution.t, probabilities_raw, labels_raw,
      loglog=True
    )

# Apply identical formatting to every enabled figure.
    for axes_set in (axes_raw, axes_avg, axes_loglog):
        if axes_set is None:
            continue

        ax = axes_set[i]

        if omega_prime_mode == "val":
            ax.set_title(
                rf"$|\omega'|={omega_prime_panel:g}\,\mathrm{{s}}^{{-1}}$",
                fontsize=16
            )
        else:
            ax.set_title(rf"$T={T_panel:g}\,\mathrm{{s}}$", fontsize=18)

        ax.set_xlabel(r"$t\,[\mathrm{s}]$", fontsize=18)

        if i % ncols == 0:
            ax.set_ylabel("Probability", fontsize=18)

        ax.tick_params(axis="both", labelsize=15)
        ax.grid(True, which="both")

print(f"\nSimulation time: {time.perf_counter() - start_time:.3f} seconds")

if omega_prime_mode == "const":
    omega_prime_title = rf"$\omega'={omega_prime_const:g}\,\mathrm{{s}}^{{-1}}$"
    filename_stem = "eight_state_constant_omega_prime"
elif omega_prime_mode == "time":
    slope = (omega_prime_final - omega_prime_initial) / T
    omega_prime_title = (rf"$\omega'(t)={omega_prime_initial:g}\,\mathrm{{s}}^{{-1}}"
                         rf"{slope:+g}t\,\mathrm{{s}}^{{-2}}$")
    filename_stem = "eight_state_linear_time_dependent_omega_prime"
else:
    omega_prime_title = rf"$|\omega'_k|={omega_prime_start:g}+k({omega_prime_step:g})$"
    filename_stem = "eight_state_omega_prime_value_scan"

def finish_figure(fig, axes, name, filename):
    if omega_prime_mode == "val":
        for ax in axes[number_of_plots:]:
            ax.set_visible(False)
    handles, labels = axes[0].get_legend_handles_labels()
    fig.suptitle(
        name + ": "
        + rf"$\boldsymbol{{\omega}}=({omega_1:g},{omega_2:g},{omega_3:g})$, "
        + omega_prime_title + ", "
        + rf"$\varepsilon={epsilon:g}$, "
        + rf"$\alpha/\varepsilon={alpha_over_epsilon:g}$",
        fontsize=20, y=0.96
    )
    fig.legend(handles, labels, loc="upper center", ncol=5, fontsize=20,
               bbox_to_anchor=(0.5, 0.88))
    fig.tight_layout(rect=[0, 0, 1, 0.80])
    fig.savefig(filename, dpi=300, bbox_inches="tight")

if fig_raw is not None:
    finish_figure(fig_raw, axes_raw, "8-state raw probabilities",
                  filename_stem + "_raw_probabilities.png")
if fig_avg is not None:
    finish_figure(fig_avg, axes_avg, "8-state running time averages",
                  filename_stem + "_running_time_averages.png")
if fig_loglog is not None:
    finish_figure(fig_loglog, axes_loglog, "8-state raw probabilities (log-log)",
                  filename_stem + "_raw_probabilities_loglog.png")

plt.show()

